wandb_version: 1

checkpoint:
  desc: null
  value: Data/checkpoint22.pth
learning_rate:
  desc: null
  value: 1.0e-05
architecture:
  desc: null
  value: FNN 128, 258, 512, 128, 64, 4
Schedule:
  desc: null
  value: 5000, 10000, 15000
epochs:
  desc: null
  value: 200000
start_epoch:
  desc: null
  value: 0
decay:
  desc: null
  value: 20000
gamma:
  desc: null
  value: 0.99
batch_size:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707216017.301833
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
